# -*- coding: utf-8 -*-
"""ML_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SCYApcQMTnTWyXxFZ0ELcRNCPAf_IMfJ

# 🎓 Predicting Student Mental Health Score from Social Media Usage

**Problem:** We're predicting a student's `Mental_Health_Score` (a continuous score from ~3 to ~10) using their social media habits, study time, sleep, physical activity, and stress level. This is a **regression** problem since the target is a number, not a category.

**Dataset:** `Student_Social_Media_And_Mental_Health_Impact.csv` — 5,000 students, 13 columns covering demographics (Age, Gender, Country), platform usage (Avg_Daily_Usage_Hours, Daily_Unlocks, Most_Used_Platform), lifestyle (Study_Hours, Sleep_Hours_Per_Night, Physical_Activity_Hours), and Stress_Level.

## 1. Import Libraries

We're grouping imports by purpose: data handling, visualization, preprocessing, models, evaluation, and saving. Keeping imports grouped like this makes it easy to see at a glance what the notebook is going to do.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""## 2. Load the Dataset

We load the CSV and take a first look at its shape and the first few rows. This is always the very first step — you can't make any decisions about a dataset until you've actually looked at it.
"""

df = pd.read_csv('/content/Student Social Media And Mental Health Impact.csv')

df.describe()

#Looking for number of rows and columns.
df.shape

#Look at first 5 rows.
df.head()

"""📌 **Reading this:** Zero duplicate rows. Nothing to remove here, but we always check — silently keeping duplicate rows can quietly bias a model toward whatever got repeated."""

df.isnull().sum()

df.duplicated().sum()

df.info()

df.describe()

"""📌 **Reading this:** Most columns look reasonable — but look closely at `Physical_Activity_Hours`: the **minimum value is -0.4**. Negative hours aren't physically possible, so this is a data-entry glitch, not a real value. We'll fix this properly in the **Data Cleaning** step below instead of ignoring it.

## 4. Exploratory Data Analysis (EDA)

We'll keep this focused — six plots, each answering one specific question about the data, not a wall of charts for the sake of it.

### 4.1 — Distribution of the target (`Mental_Health_Score`)

Before predicting anything, we need to understand the shape of what we're predicting.
"""

sns.histplot(df['Mental_Health_Score'], kde=True)

"""### 4.2 — Correlation heatmap

Which numeric features actually move together with the target?
"""

sns.heatmap(df.corr(numeric_only=True), annot=True)

"""### 4.3 — Stress Level vs Mental Health Score

Does higher stress genuinely come with a lower score?
"""

df['Stress_Level'].unique()

order=['Medium', 'Low', 'Very High', 'High']
sns.boxplot(x='Stress_Level',y='Mental_Health_Score',data=df)

df.select_dtypes(include='number')

"""### 4.4 — Daily Usage Hours vs Mental Health Score

Does more time on social media relate to a lower score?
"""

sns.scatterplot(x='Avg_Daily_Usage_Hours',y='Mental_Health_Score',data=df)

platform_counts=df["Most_Used_Platform"].value_counts()
platform_counts

plt.figure(figsize=(9,5))
# decsending
sns.countplot(x=df['Most_Used_Platform'],order=df['Most_Used_Platform'].value_counts().index)

"""### 4.5 — Sleep Hours vs Mental Health Score

Sleep is one of the most commonly cited mental health factors — does the data back that up?
"""

print(df['Sleep_Hours_Per_Night'].corr(df['Mental_Health_Score']))

"""### 4.6 — Most Used Platform (count)

A quick look at which platforms are most common in our dataset.

**Checking Outliers**
"""

num_features = df.select_dtypes(include='number') #int64 or float64
Q1  = num_features.quantile(0.25)
Q3  = num_features.quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = (num_features < lower_bound) | (num_features > upper_bound)
print(outliers.sum())

"""## 5. Data Cleaning

Two real issues to fix here — everything else in this dataset is already clean, so we don't manufacture cleaning steps that aren't needed.
"""

# drop duplicates
df=df.drop_duplicates()
# converting -ve or relaictic value to relaistic
df['Physical_Activity_Hours']=df['Physical_Activity_Hours'].clip(lower=0)
df.describe()

"""📌 **Why `clip(lower=0)` and not dropping the row:** the rest of that student's data (age, study hours, stress level, etc.) is still valid and useful — throwing away the whole row over one bad value wastes good data. Clipping caps the impossible value at the nearest realistic one (0 hours) without discarding everything else about that student.

We're not dropping any columns either — every column here has a plausible reason to matter for predicting mental health, and we already confirmed none of them are empty or constant.

## 6. Skewness

**What skewness is:** a measure of how lopsided a numeric column's distribution is. A value near 0 means roughly symmetric (bell-shaped); a large positive or negative value means the data leans heavily to one side, with a long tail.

**Why it matters:** models like Linear Regression assume features are roughly well-behaved. A heavily skewed column (think: a long tail of extreme values) can quietly drag the model's predictions in that direction. Tree-based models like Random Forest don't care about skew — but since we're also training a Linear Regression baseline, it's worth fixing.
"""

# Differences Between Skewness and KurtosisSkewness: Measures the lack of symmetry or the "leaning" of a data curve to one side.Kurtosis: Measures how flat or peaked a distribution's top and tails are compared to a normal distribution.
num_cols=df.select_dtypes(include='number')
num_cols.skew()
# we set a threshlod
# if close to 0 -> centralized(0.0876)
# -ve<0 left skewed(-1.24)
# +ve>0 right skewed(1.34)


# we have to cure skewness we use log transformation

"""## 7. Feature Engineering

**One meaningful engineered feature here:** grouping `Country`.

- `Country` has **111 unique values** in this dataset — one-hot encoding that directly would add 110+ mostly-empty columns, which hurts the model far more than it helps (this is called high cardinality).
- Dropping `Country` entirely throws away real signal — a student's country genuinely correlates with things like internet access, culture, and sleep norms.
- **The fix:** keep the top 10 most frequent countries as their own category, and bucket everything else into `"Other"`. We keep the signal that matters and lose the noise that doesn't.
"""

rel_countries=df['Country'].value_counts().index[:10].tolist()

def grp_countries(country):
  if country in rel_countries:
    return country
  else:
    return 'Other'

df['Grouped_Country']=df['Country'].apply(grp_countries)

df['Grouped_Country'].value_counts().index[:10].to_list()

"""📌 **Result:** we went from 111 raw categories down to 11 manageable ones (10 countries + "Other"). This is exactly the kind of decision that separates a project that "just ran `pd.get_dummies()`" from one that actually thought about the data.

## 8. Encoding Strategy

Before we jump into code, let's decide *how* each categorical column should be encoded — this decision matters more than the code itself.

- **`Stress_Level` → Ordinal Encoding.** Its categories have a real, meaningful order: Low < Medium < High < Very High. We already saw in EDA (section 4.3) that the score drops step by step as stress increases — encoding it as 0, 1, 2, 3 preserves that order for the model.
- **`Gender`, `Academic_Level`, `Most_Used_Platform`, `Purpose_Of_Use`, `Country_Grouped` → One-Hot Encoding.** These categories have **no natural order** — "Instagram" isn't "greater than" "LinkedIn". One-hot encoding creates a separate 0/1 column per category so the model doesn't accidentally assume a false ranking.

We'll implement both of these inside a single `ColumnTransformer` in the next step, rather than doing it manually column by column — that keeps preprocessing consistent and reusable.
"""

# encodinng strategy
# ordinal-> order depenceny stress level
# one hot-> every other object col

"""## 9. Train-Test Split

**Why we split:** we need data the model has never seen to honestly check how well it generalizes. If we evaluate on the same data we trained on, the model can just "memorize" the answers and look artificially good.

**Common ratios:** 80/20 or 70/30 are both standard. We'll use an 80/20 split here — with 5,000 rows, that still leaves 1,000 rows for a solid, reliable test.

We split **before** fitting any preprocessing — this is the single most common beginner mistake (called data leakage), and we'll avoid it by fitting everything only on the training set.
"""

# train test split
from sklearn.model_selection import train_test_split
# never aplly prepossceeing on testing col casue data leakage
skews_col=df["Study_Hours"] # log transformation

# standard scalar
other_numeric_col=df[['Age',
'Avg_Daily_Usage_Hours',
'Daily_Unlocks',
'Physical_Activity_Hours',
'Sleep_Hours_Per_Night',
'Mental_Health_Score']]
# ordinal encoding

ordinal_col=df["Stress_Level"]
# one hot ecoding
nominal_col=df[["Gender",
"Academic_Level",
"Most_Used_Platform",
"Purpose_Of_Use",
"Grouped_Country"]]

feature_cols=pd.concat([skews_col,other_numeric_col,ordinal_col,nominal_col],axis=1)
X=feature_cols
y=df["Mental_Health_Score"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

"""## 10. Preprocessing using ColumnTransformer

Our columns need **different treatment**:

- `Study_Hours` (the skewed one) → impute → `log1p` transform → scale
- The other numeric columns → impute → scale (no skew to fix)
- `Stress_Level` → impute → `OrdinalEncoder` with an **explicit order**
- The nominal columns → impute → `OneHotEncoder`

We include a `SimpleImputer` in every branch even though this dataset has zero missing values right now — it's a safety net. Real-world data (and our future API's incoming requests) won't always be this clean, and a pipeline that assumes "no missing values ever" is a pipeline that breaks in production.

`ColumnTransformer` glues all of this into **one object** that applies the right transformation to the right column type in a single `.fit()` / `.transform()` call — no manual column-by-column juggling.

## 11. Build a Pipeline

**Why Pipeline matters:** a `Pipeline` chains preprocessing and the model into a single object. Calling `.fit()` once does both steps in the correct order, and calling `.predict()` on brand-new raw data automatically applies the exact same preprocessing that was used during training — no risk of forgetting a step or applying it inconsistently.

**Why companies prefer this:** when this model gets deployed (which we're doing in Part 2 with FastAPI), the API doesn't need to know *anything* about scaling, encoding, or log transforms — it just loads one saved pipeline object and calls `.predict()` on raw input. That's a huge reduction in what can go wrong in production.

We'll build two pipelines below — one per model — so we can fairly compare them.
"""

# all 4 pipelines are craeted

"""## 12. Model Building

We're comparing **two models** here because the comparison itself teaches something useful — a plain Linear Regression baseline versus a Random Forest, which can capture the non-linear patterns we spotted back in EDA (section 4.4).
"""

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder,OrdinalEncoder,FunctionTransformer
from sklearn.compose import ColumnTransformer

skew_pipeline=Pipeline(steps=[
  ('log_transformation',FunctionTransformer(np.log1p)),
  ('scaler',StandardScaler())
])

plain_pipeline=Pipeline(steps=[
    ('scale',StandardScaler())
])

ordinal_pipeline=Pipeline(steps=[
    ('encode',OrdinalEncoder(categories=[[
        'Low','Medium','High','Very High'
    ]]))
])

nomial_pipeline=Pipeline(steps=[
    ('encode',OneHotEncoder(handle_unknown='ignore'))

])

preprocessor = ColumnTransformer(transformers=[
    ('skewed_features', skew_pipeline, [skews_col.name]),
    ('numeric_features', plain_pipeline, other_numeric_col.columns.tolist()),
    ('ordinal_features', ordinal_pipeline, [ordinal_col.name]),
    ('nominal_features', nomial_pipeline, nominal_col.columns.tolist())
])

preprocessor

"""### 12.1 — Baseline: Linear Regression"""

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_squared_error
)
import numpy as np

# Linear Regression Pipeline
lr_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

# Train
lr_pipeline.fit(X_train, y_train)

# Predictions
lr_preds_train = lr_pipeline.predict(X_train)
lr_preds_test  = lr_pipeline.predict(X_test)

# Metrics
train_r2 = r2_score(y_train, lr_preds_train)
test_r2  = r2_score(y_test, lr_preds_test)

mae  = mean_absolute_error(y_test, lr_preds_test)
mse  = mean_squared_error(y_test, lr_preds_test)
rmse = np.sqrt(mse)

# Results
print("=" * 55)
print(" Linear Regression Performance")
print("=" * 55)

print(f" Training Accuracy (R²) : {train_r2:.4f} ({train_r2*100:.2f}%)")
print(f" Testing Accuracy (R²)  : {test_r2:.4f} ({test_r2*100:.2f}%)")

print("-" * 55)

print(f" Mean Absolute Error    : {mae:.2f}")
print(f" Mean Squared Error     : {mse:.2f}")
print(f" Root Mean Squared Error: {rmse:.2f}")

print("=" * 55)

"""### 12.2 — Random Forest (default settings)

Same preprocessor, different model at the end — that's the entire point of building the pipeline once.
"""

from sklearn.ensemble import RandomForestRegressor

# Random Forest Pipeline
rf_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(random_state=42))
])

rf_pipeline.fit(X_train, y_train)

rf_preds_train = rf_pipeline.predict(X_train)
rf_preds_test  = rf_pipeline.predict(X_test)

train_r2 = r2_score(y_train, rf_preds_train)
test_r2  = r2_score(y_test, rf_preds_test)

mae  = mean_absolute_error(y_test, rf_preds_test)
mse  = mean_squared_error(y_test, rf_preds_test)
rmse = np.sqrt(mse)

print(f"Accuracy of Training {train_r2*100} %")
print(f"Accuracy of Testing {test_r2*100} %")
print(f"MAE : {mae}")
print(f"MSE : {mse}")
print(f"RMSE : {np.sqrt(mse)}")

"""### 12.3 — Hyperparameter Tuning the Random Forest

When tuning a `Pipeline`, each parameter needs to be prefixed with the step name (`regressor__`) so `RandomizedSearchCV` knows which part of the pipeline it belongs to. We use `RandomizedSearchCV` instead of a full grid search — it samples a fixed number of combinations instead of testing every single one, which is far faster while still finding a strong set of parameters.
"""

from sklearn.model_selection import RandomizedSearchCV

# Random Forest Pipeline

param_grid={
    'regressor__n_estimators':[100,200,300],
    'regressor__max_depth':[5,10,15],
    'regressor__min_samples_split':[2,5,10],
    'regressor__min_samples_leaf':[1,2,4]
}

random_search_cv=RandomizedSearchCV(
    estimator=rf_pipeline,
    param_distributions=param_grid,
    n_iter=15,
    cv=5,
    verbose=2,
    n_jobs=-1,
    random_state=42,
    scoring='r2'


)
random_search_cv.fit(X_train,y_train)

# random search cv

random_search_cv.best_params_

rf_best_pipeline=random_search_cv.best_estimator_
rf_best_pipeline
rf_best=rf_best_pipeline.predict(X_test)

print(f"R2 Score for random forest after hyperparameter tuning {r2_score(y_test, rf_best)}")
print(f"MAE Score for random forest after hyperparameter tuning {mean_absolute_error(y_test, rf_best)}")

"""## 13. Model Evaluation

**Metrics, explained simply:**
- **R² Score** — how much of the variation in mental health scores our model explains, from 0 (useless) to 1 (perfect). 0.85 means the model explains 85% of the pattern.
- **MAE (Mean Absolute Error)** — on average, how far off our prediction is, in the original units (score points). Easy to explain to a non-technical person.
- **RMSE (Root Mean Squared Error)** — similar to MAE, but penalizes big mistakes more heavily. Useful for spotting whether a model makes a few very wrong predictions.

Cross-validation R² (from tuning, above) tells us how good the model is across many different train/validation splits — the real, honest test is still the untouched test set below.
"""

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import pandas as pd
import numpy as np

# Calculate metrics for Linear Regression
lr_r2_testing = r2_score(y_test, lr_preds_test)
lr_r2_training = r2_score(y_train, lr_preds_train)
lr_mae = mean_absolute_error(y_test, lr_preds_test)
lr_rmse = np.sqrt(mean_squared_error(y_test, lr_preds_test))

# Calculate RMSE for default Random Forest
rf_rmse = np.sqrt(mean_squared_error(y_test, rf_preds_test))

# Calculate RMSE for tuned Random Forest
rf_tuned_preds          = random_search_cv.best_estimator_.predict(X_test)
rf_tuned_rmse           = np.sqrt(mean_squared_error(y_test, rf_tuned_preds))
rf_tuned_training_preds = random_search_cv.best_estimator_.predict(X_train)
r2_tuned_training       = r2_score(y_train, rf_tuned_training_preds)
rf_tuned_mae            = mean_absolute_error(y_test, rf_tuned_preds)
rf_tuned_r2             = r2_score(y_test, rf_tuned_preds)


# Create a DataFrame to consolidate results
results = pd.DataFrame({
    'Model': ['Linear Regression', 'Random Forest (default)', 'Random Forest (tuned)'],
    'R2': [lr_r2_testing, test_r2, rf_tuned_r2],
    'Training R2': [lr_r2_training, train_r2, r2_tuned_training],
    'MAE': [lr_mae, mae, rf_tuned_mae],
    'RMSE': [lr_rmse, rf_rmse, rf_tuned_rmse]
})

print(results)

"""## 14. Save the Model

We save the **entire pipeline** — preprocessing and model together — as a single file, not just the raw model. **Why:** if we only saved the Random Forest object, our FastAPI backend would need to manually recreate every encoding and scaling step by hand at prediction time, which is fragile and easy to get wrong. Saving the full pipeline means the backend just loads one file and calls `.predict()` on raw input — the pipeline handles everything internally, exactly the same way it did during training.
"""

import joblib
joblib.dump(random_search_cv.best_estimator_,'mental_health_pipeline.pkl')

"""
#**Next steps (Part 2):**
build a FastAPI backend with Pydantic request validation that loads `mental_health_pipeline.pkl` and exposes a `/predict` endpoint, then connect a simple frontend, then deploy both so this becomes a live, clickable demo.
"""



